name: MergeCI
on: [ pull-request ]
jobs: 
  MergeJob:
    runs-on: ${{ matrix-os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - run: python main.py